//
// Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
//
// On Wed Dec  5 19:05:27 UTC 2018
//
//
// Ports:
// Name                         I/O  size props
// led                            O     1
// CLK                            I     1 unused
// RST                            I     1 unused
// led_val                        I     1
//
// Combinational paths from inputs to outputs:
//   led_val -> led
//
//
// This is the module to control the built-in LED
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkLED(CLK,
	     RST,

	     led_val,
	     led);
  input  CLK;
  input  RST;

  // value method led
  input  led_val;
  output led;

  // signals for module outputs
  wire led;

  // value method led
  assign led = led_val ;
endmodule  // mkLED

