//
// Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
//
// On Wed Dec  5 19:11:58 UTC 2018
//
//
// Ports:
// Name                         I/O  size props
// PIN_24                         O     1
// RDY_led                        O     1 const
// USBPU                          O     1 const
// RDY_usbpu                      O     1 const
// CLK_slow_clock                 O     1 clock
// CLK_GATE_slow_clock            O     1 const
// CLK                            I     1 clock
// RST                            I     1 unused
//
// No combinational paths from inputs to outputs
//
//
// Define BSV_POSITIVE_RESET if there is no reset pin in order to prevent the program from resetting
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTB(CLK,
	    RST,

	    PIN_24,
	    RDY_led,

	    USBPU,
	    RDY_usbpu,

	    CLK_slow_clock,
	    CLK_GATE_slow_clock);
  input  CLK;
  input  RST;

  // value method led
  output PIN_24;
  output RDY_led;

  // value method usbpu
  output USBPU;
  output RDY_usbpu;

  // oscillator and gates for output clock CLK_slow_clock
  output CLK_slow_clock;
  output CLK_GATE_slow_clock;

  // signals for module outputs
  wire CLK_GATE_slow_clock, CLK_slow_clock, PIN_24, RDY_led, RDY_usbpu, USBPU;

  // register counter
  reg [4 : 0] counter;
  wire [4 : 0] counter$D_IN;
  wire counter$EN;

  // ports of submodule c1
  wire c1$CLK_OUT;

  // ports of submodule led1
  wire led1$led, led1$led_val;

  // remaining internal signals
  wire [31 : 0] _0b101010001110111011100010101__q1;

  // oscillator and gates for output clock CLK_slow_clock
  assign CLK_slow_clock = c1$CLK_OUT ;
  assign CLK_GATE_slow_clock = 1'b1 ;

  // value method led
  assign PIN_24 = led1$led ;
  assign RDY_led = 1'd1 ;

  // value method usbpu
  assign USBPU = 1'b0 ;
  assign RDY_usbpu = 1'd1 ;

  // submodule c1
  ClockDiv #(.width(32'd21),
	     .lower(32'd248576),
	     .upper(32'd1848575),
	     .offset(32'd0)) c1(.CLK_IN(CLK),
				.RST(!`BSV_RESET_VALUE),
				.PREEDGE(),
				.CLK_OUT(c1$CLK_OUT));

  // submodule led1
  mkLED led1(.CLK(CLK),
	     .RST(!`BSV_RESET_VALUE),
	     .led_val(led1$led_val),
	     .led(led1$led));

  // register counter
  assign counter$D_IN = counter + 5'd1 ;
  assign counter$EN = 1'd1 ;

  // submodule led1
  assign led1$led_val = _0b101010001110111011100010101__q1[counter] ;

  // remaining internal signals
  assign _0b101010001110111011100010101__q1 =
	     32'b00000101010001110111011100010101 ;

  // handling of inlined registers

  always@(posedge c1$CLK_OUT)
  begin
    if (!`BSV_RESET_VALUE == `BSV_RESET_VALUE)
      begin
        counter <= `BSV_ASSIGNMENT_DELAY 5'd0;
      end
    else
      begin
        if (counter$EN) counter <= `BSV_ASSIGNMENT_DELAY counter$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    counter = 5'h0A;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTB

